// <auto-generated />
using LukmankhakimDarkhan_Console_App_Lesson_4;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LukmankhakimDarkhan_Console_App_Lesson_4.Migrations
{
    [DbContext(typeof(Entity_Framework_Core))]
    partial class Entity_Framework_CoreModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LukmankhakimDarkhan_Console_App_Lesson_4.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogId"), 1L, 1);

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            BlogId = 1,
                            AuthorName = "Nurik",
                            Content = "I'm Mickelangelo.",
                            LikeCount = 10000000,
                            Url = "cartoonnetwork.com"
                        },
                        new
                        {
                            BlogId = 2,
                            AuthorName = "Katiya",
                            Content = "I'm Batman.",
                            LikeCount = 10000000,
                            Url = "tiktok.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
